# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Taskpoet < Formula
  desc "Alternative to the awesome TaskWarrior, but in Go, with some additional stuff I find useful"
  homepage "https://github.com/drewstinnett/taskpoet"
  version "0.0.3"
  license "BSD-2-Clause"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/drewstinnett/taskpoet/releases/download/v0.0.3/taskpoet-0.0.3_macOS_amd64.tar.gz"
      sha256 "cc9bd75bcda8540fe18c5c0814782dd40cab581ba57dc6426d2754f23073a683"
    end
    if Hardware::CPU.arm?
      url "https://github.com/drewstinnett/taskpoet/releases/download/v0.0.3/taskpoet-0.0.3_macOS_arm64.tar.gz"
      sha256 "96df9a1bb4864576b7b54998ae2c5e5247716ddb2348d44b08ac12a8c8d3b76e"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/drewstinnett/taskpoet/releases/download/v0.0.3/taskpoet-0.0.3_linux_amd64.tar.gz"
      sha256 "33301c45fc12cd82df8ba7fda365d2346ff879f27e1b8c1b36a0c8e282ab85ad"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/drewstinnett/taskpoet/releases/download/v0.0.3/taskpoet-0.0.3_linux_arm64.tar.gz"
      sha256 "6b9190027cef83c76b8ade32e0de18ace553a43df675620daacb087f16cc6b3a"
    end
  end

  def install
    bin.install "taskpoet"
  end

  def caveats; <<~EOS
    Add the following in your ~/.zshrc or ~/.profile for faster typin':

      alias tp="#{opt_bin}/taskpoet"
  EOS
  end
end
